### ISSUE TITLE
Inventory session exploration and creation

### ISSUE THREAD

**Issue by tperale** [Sprtch/huron#38]
This issue relies on this issue https://github.com/Sprtch/despinassy/issues/6 from despinassy repository.

Add creation of new inventory session and record-keeping to explore the previous session already archived.

### Roadmap

- [ ] Add a archive button and API endpoint to archive the current inventory session
- [ ] Modify `inventory` API endpoint to work only on the last session
- [ ] Modify `inventory` react model to also keep track of the inventory session
- [ ] Navigate through records of previous inventory

**Comment by tperale** [comment]
The API is solved with this commit https://github.com/Sprtch/huron/commit/dc92b26fbf7ef078d04e3780359df05e380d3655

**Comment by tperale** [comment]
The function for the _archive_ button are present in https://github.com/Sprtch/huron/commit/879b713e44f26407ae1b021d7f7e3ae9b1f2f423 but will require admin privilege later.
